
tasks:
  - init: npm install && npm run build
    command: |
      export HMR_HOST=`gp url 3000`
      npm run dev

ports:
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - svelte.svelte-vscode

    - esbenp.prettier-vscode

    - formulahendry.auto-rename-tag

    - formulahendry.auto-close-tag

    - HookyQR.beautify

    - mikestead.dotenv

    - GitHub.github-vscode-theme

    - oderwat.indent-rainbow

    - christian-kohler.path-intellisense

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
